import { useState } from "react";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { DateTime } from "luxon";
import Head from "next/head";
import { AuthShowcase, NavBar } from "~/components";
import { useSession } from "next-auth/react";
 
export default function Page() {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const { id } = router.query;
  const petId = parseInt(id, 10);

  const {
    data: pet,
    refetch: refetchPet,
    isLoading,
  } = api.pet.getPetById.useQuery({ petId });

  const userId = pet?.data.userId;

  const {
    data: user,
    isLoading: userIsLoading,
  } = api.user.getUserById.useQuery({ userId });

  const updatedAtDate = new Date(pet?.data.updatedAt);

  const formattedDate = updatedAtDate.toLocaleString(DateTime.DATETIME_MED);

  return(
    <>    
    <Head>
    <title>🐾 MichiAPP | {pet?.data.name}</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <NavBar />
  <main className="flex min-h-screen flex-col items-center justify-center">
    {sessionData ? (
      <>
      <h1>Mascota {petId}: {pet?.data.name}</h1>
      <p>Edad: {pet?.data.age}</p>
      <p>Tipo: {pet?.data.category}</p>
      <p>Raza: {pet?.data.breed}</p>
      <p>Peso: {pet?.data.weight}</p>
      <p>Adoptado: {pet?.data.adopted}</p>
      <p>Última Actualización: {formattedDate}</p>
      {userIsLoading ? (
        <p>Cargando usuario...</p>
      ) : (
        <p>Usuario Creador: {user?.data.name}</p>
      )}
      <p>Descripción: {pet?.data.description}</p>
      <p>Características: {pet?.data.characteristics}</p>
      </>
    ) : (
      <>
        <h1 className="text-5xl uppercase text-primary">🐾 MichiAPP</h1>
        <AuthShowcase />
      </>
    )}
  </main>
    </>
  )
}

