import Head from "next/head";
import { useSession } from "next-auth/react";
import { NavBar } from "~/components";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

const index = () => {
  return (
    <>
    <Head>
      <title>MichiAPP | ONGs</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <>
      <NavBar />
      <main
        className={`${poppins.className} flex min-h-screen flex-col px-5 md:px-20`}
      >
        <h1 className="mt-10 text-3xl font-[500] text-neutral">ONGs</h1>
      </main>
    </>
  </>
  )
}

export default index