import Head from "next/head";
import { useSession } from "next-auth/react";
import { NavBar, PetCard } from "~/components";
import { Poppins } from "next/font/google";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { api } from "~/utils/api";
import { BiRefresh } from "react-icons/bi";
import { AiFillAlert, AiFillHeart } from "react-icons/ai";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

const index = () => {
  const { data: sessionData } = useSession();
  // const router = useRouter();

  // useEffect(() => {
  //   if (!sessionData) {
  //     router.push('/');
  //   }
  // }, [sessionData, router]);

  const userId = sessionData?.user?.id;

  const pets = api.pet.getLikedPets.useQuery({ userId }).data;

  return (
    <>
      <Head>
        <title>MichiAPP | Favoritos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <NavBar />
        <main
          className={`${poppins.className} flex min-h-screen flex-col px-5 md:px-20`}
        >
          <h1 className="mt-10 text-3xl font-[500] text-neutral">Favoritos</h1>
          <div className="flex flex-row flex-wrap justify-between gap-4 md:justify-start">
            {pets?.length === 0 ? (
              <div className="text-center text-error mx-auto text-xs">
                <p className="uppercase">Aún no tienes favoritos</p>
                <AiFillHeart className="text-3xl mx-auto"/>
              </div>
            ) : (
              pets?.map((pet) => (
                <PetCard
                  key={pet.id}
                  name={pet.name}
                  age={pet.age}
                  gender={pet.gender}
                  description={pet.description}
                  image={pet.image}
                  id={pet.id}
                  adopted={pet.adopted}
                  weight={pet.weight}
                  characteristics={pet.characteristics}
                  liked={pet.liked}
                  userId={sessionData?.user?.id}
                  phone={pet.phone}
                  creatorId={pet.userId}
                />
              ))
            )}
          </div>
        </main>
      </>
    </>
  );
};

export default index;
