import Head from "next/head";
import { AuthShowcase, AllPetsListPublic } from "~/components";
import { useSession } from "next-auth/react";


export default function Home() {

  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>🐾 MichiAPP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sessionData ? (
        <main className="flex min-h-screen flex-col items-center">
          <AllPetsListPublic />
        </main>
      ) : (
        <main className="flex min-h-screen flex-col items-center justify-center p-[20px] py-[150px]">
          <h1 className="text-5xl uppercase text-primary">🐾 MichiAPP</h1>
          <AuthShowcase />
        </main>
      )}
    </>
  );
}

