import Head from "next/head";
import {
  RegisterButton,
  NavBar,
  LoginButton,
  RandomPetsHero,
  MainOngs,
  MainPets,
} from "~/components";
import { useSession } from "next-auth/react";
import { useState, useEffect } from "react";
import { logo } from "~/assets";
import Image from "next/image";
import { Poppins } from "next/font/google";
import { AiOutlineSearch } from "react-icons/ai";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function Home() {
  const { data: sessionData } = useSession();
  const [showContent, setShowContent] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => {
      setShowContent(true);
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <Head>
        <title>MichiAPP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sessionData ? (
        <>
          <NavBar />
          <main
            className={`${poppins.className} flex min-h-screen flex-col px-5 md:px-20`}
          >
            <div className="mt-12 flex h-9 w-full flex-row items-center justify-between rounded-3xl border px-4 md:w-[50%] md:mx-auto">
                <input type="text" placeholder="Buscar" className="w-full bg-transparent outline-none text-sm" />
                <button type="submit" className="ml-2 outline-none focus:outline-none">
                  <AiOutlineSearch className="text-xl opacity-40" />
                </button>
            </div>
            <RandomPetsHero />
            <MainPets />
            <MainOngs />
          </main>
        </>
      ) : (
        <main
          className={`${poppins.className} flex min-h-screen flex-col items-center justify-start`}
        >
          <div
            className={`green-degrade flex w-full flex-col items-center justify-center duration-1000 ease-in ${
              !showContent ? "h-screen" : "h-[300px] rounded-b-[41px] shadow-md"
            }`}
          >
            <Image src={logo} alt="logo" />
          </div>

          <h1 className="mt-12 text-center text-[32px] font-[500] text-primary">
            Adoptá tu mascota
          </h1>
          <p className="mb-12 mt-2 text-center text-xs opacity-50">
            Elige la adopción y descubrí el amor incondicional
            <br /> de una mascota rescatada
          </p>
          <RegisterButton />
          <LoginButton />
        </main>
      )}
    </>
  );
}
