import Head from "next/head";
import { api } from "~/utils/api";
import { useSession } from "next-auth/react";
import { AuthShowcase } from "~/components";


export default function Home() {

  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Patitas del Sur</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sessionData ? (
        <main className="flex min-h-screen flex-col items-center justify-around p-[20px]">
          <h1 className="text-3xl uppercase text-primary">Patitas del Sur</h1>
          <h2>Bienvenido {sessionData.user.name}</h2>
        </main>
      ) : (
        <main className="flex min-h-screen flex-col items-center justify-between p-[20px] py-[150px]">
          <h1>Patitas del Sur</h1>
          <AuthShowcase />
        </main>
      )}
    </>
  );
}

