import Head from "next/head";
import { NewPetForm } from "~/components"
import {NavBar} from "~/components";
import { useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useRouter } from "next/router";

const newpet = () => {
  const router = useRouter();
  const { data: sessionData } = useSession();

  const {
    data: user,
    refetch: refetchUser,
  } = api.user.getUserById.useQuery({ userId: sessionData?.user.id });

  const isAdmin = user?.data.isAdmin;

  if (!isAdmin) {
    void router.push("/");
  }
  
  return (
    <>
      <Head>
        <title>🐾 MichiAPP | ADMIN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <>
          <NavBar />
          <main className="flex min-h-screen flex-col items-center">
            <NewPetForm />
          </main>
        </>
    </>
  );
};

export default newpet