import Head from "next/head";
import { AdminPetsList } from "~/components";
import {NavBar} from "~/components";
import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { useState } from "react";

const Admin = () => {
  const router = useRouter();
  const { data: sessionData } = useSession();

  const {
    data: user,
    refetch: refetchUser,
  } = api.user.getUserById.useQuery({ userId: sessionData?.user.id });

  const isAdmin = user?.data.isAdmin;

  return (
    <>
      <Head>
        <title>🐾 MichiAPP | ADMIN</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <>
          <NavBar />
          <main className="flex min-h-screen flex-col items-center">
            <AdminPetsList  />
          </main>
        </>
    </>
  );
};

export default Admin;
